### ISSUE TITLE
Can't view climber label

### ISSUE THREAD

**Issue by Scutterman** [Scutterman/ascii-lemmings-wasm#31]
stack trace:
```
00049cd2:0x3a7b Uncaught RuntimeError: unreachable
    at assembly/actions/lemmingAction/LemmingAction#label@virtual (<anonymous>:wasm-function[277]:0x3a7b)
    at assembly/levels/level/Level#processLemmingSelect (<anonymous>:wasm-function[411]:0x79bd)
    at assembly/levels/baseLevel/BaseLevel#processLemmingSelect@virtual (<anonymous>:wasm-function[241]:0x3762)
    at assembly/loop/processInputs (<anonymous>:wasm-function[395]:0x6de3)
    at assembly/loop/eventLoop (<anonymous>:wasm-function[399]:0x6fe9)
    at assembly/loop/triggerEventLoop (<anonymous>:wasm-function[207]:0x33a6)
    at loop (http://localhost:8080/wasmRunner.js:75:33)
    at onmessage (http://localhost:8080/wasmRunner.js:34:5)
```

Probably related to issue https://github.com/AssemblyScript/assemblyscript/issues/1635 where it seems like the compiler isn't populating the br_table correctly

**Comment by Scutterman** [comment]
It might be possible to solve this by combining the "Lemming" and "LemmingAction" classes. The level would contain an array of LemmingActions instead of Lemmings, and the update code would return null if no change was made to the action or a new object to swap into the correct LemmingAction[] index if the action has changed. This would mean that every time the action changes, the lemming object is destroyed and one with a different subclass is returned.

Would be much better to fix at source though.

**Comment by Scutterman** [comment]
I couldn't create a reproduction today but I have an idea. The code which calls label must be called before the code which calls update and before the climb class has been referenced. Perhaps start off with a Fall class that has an extra method which calls Label. This extra method is called in the index file. Then in its update method it can return a Walk

**Comment by Scutterman** [comment]
We created the reproduction and commented on the issue & PR
https://github.com/AssemblyScript/assemblyscript/issues/2034
https://github.com/AssemblyScript/assemblyscript/pull/2040

**Comment by Scutterman** [comment]
We've added a temporary fix using `idof<Climb>()` in the `LemmingAction` class.
